version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      golang: 1.21
    commands:
      - cd backend/nodejs
      - npm install --quiet
      - cd ..
      
  build:
    commands:
      - cd nodejs
      - npm run build
      - cp ../infrastructure/backend.yml .
      - aws cloudformation package --template-file backend.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
      - cd ..
      
      - cd workers/processor
      - go build -o processor ./cmd/processor
      - cd ../..
      
  post_build:
    commands:
      - cd nodejs
      - rm -rf node_modules
      - npm prune --omit=dev --quiet
      - rm -rf dist/workers/*
      - cd ..

artifacts:
  files:
    - nodejs/template-export.yml
    - nodejs/dist/**/*
    - nodejs/package.json
    - nodejs/package-lock.json
    - workers/processor/processor
    - workers/processor/Dockerfile
  base-directory: backend