version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      golang: 1.21
    commands:
      - cd backend/nodejs
      - npm install --quiet
      - cd ..
      
  build:
    commands:
      - cd nodejs
      - npm run build
      - cp ../../infrastructure/backend.yml .
      - aws cloudformation package --template-file backend.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
      - cd ..
      
      - cd workers/processor
      - go build -o processor ./cmd/processor
      - echo "Building Docker image..."
      - docker build -t $ECR_REPOSITORY:latest .
      - docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:latest
      - cd ../..
      
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      - cd nodejs
      - rm -rf node_modules
      - npm prune --omit=dev --quiet
      - rm -rf dist/workers/*
      - cd ..

artifacts:
  files:
    - nodejs/template-export.yml
    - nodejs/dist/**/*
    - nodejs/package.json
    - nodejs/package-lock.json
  base-directory: backend