# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - mkdir -p ffmpeg-download
      - cd ffmpeg-download
      - curl -s -O https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-arm64-static.tar.xz
      - tar xf ffmpeg-git-arm64-static.tar.xz
      - cd ..

      - cd backend/nodejs
      - npm install --quiet
      - cd src/layers/resource-layer/nodejs && npm install --quiet && cd ../../../..
      
      - mkdir -p src/layers/resource-layer/ffmpeg
      - cp ../../../../ffmpeg-download/ffmpeg-git-*/ffmpeg src/layers/resource-layer/ffmpeg/
      - cp ../../../../ffmpeg-download/ffmpeg-git-*/ffprobe src/layers/resource-layer/ffmpeg/
      - chmod +x src/layers/resource-layer/ffmpeg/*
      - cd src/layers/resource-layer
      - zip -q -r ../../../resource-layer.zip nodejs ffmpeg
      - cd ../../../
      - rm -rf src/layers/resource-layer/ffmpeg
      - cd ..
      
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      
  build:
    commands:
      - cd nodejs
      - npm run build
      - cp ../../infrastructure/backend.yml .
      - aws cloudformation package --template-file backend.yml --s3-bucket ${S3_BUCKET} --output-template-file template-export.yml
      - cd ..
      
      - cd workers/processor
      - echo "Building Docker image..."
      - export BUILD_TIME=$(date +%Y%m%d%H%M%S)
      - docker build -t ${ECR_REPOSITORY}:${BUILD_TIME} .
      - docker tag ${ECR_REPOSITORY}:${BUILD_TIME} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY}:${BUILD_TIME}
      - docker tag ${ECR_REPOSITORY}:${BUILD_TIME} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest
      - cd ../..
      
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY}:${BUILD_TIME}
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY}:latest

      - cd nodejs
      - rm -rf node_modules
      - npm prune --omit=dev --quiet
      - cd ..

artifacts:
  files:
    - nodejs/template-export.yml
    - nodejs/dist/**/*
    - nodejs/package.json
    - nodejs/package-lock.json
    - nodejs/resource-layer.zip
  base-directory: backend